/**
 * Generates src/dictionary/data.ts from a flat DICOM dictionary JSON
 * (the @ubercode/dcmtk `src/data/dictionary.json` format: 8-hex-key →
 * { vr, name, vm: [min, max|null], retired }), itself derived from DCMTK's
 * dicom.dic (OFFIS).
 *
 * Usage: node scripts/generateDictionary.mjs <path-to-dictionary.json>
 * Then:  pnpm exec prettier --write src/dictionary/data.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const STANDARD_VRS = new Set([
    'AE',
    'AS',
    'AT',
    'CS',
    'DA',
    'DS',
    'DT',
    'FD',
    'FL',
    'IS',
    'LO',
    'LT',
    'OB',
    'OD',
    'OF',
    'OL',
    'OV',
    'OW',
    'PN',
    'SH',
    'SL',
    'SQ',
    'SS',
    'ST',
    'SV',
    'TM',
    'UC',
    'UI',
    'UL',
    'UN',
    'UR',
    'US',
    'UT',
    'UV',
]);

const sourcePath = process.argv[2];
if (sourcePath === undefined) {
    console.error('usage: node scripts/generateDictionary.mjs <path-to-dictionary.json>');
    process.exit(1);
}

const raw = JSON.parse(readFileSync(sourcePath, 'utf8'));
const keys = Object.keys(raw).sort();
const lines = [];
for (const key of keys) {
    if (!/^[0-9A-F]{8}$/.test(key)) {
        throw new Error(`non-hex dictionary key: ${key}`);
    }
    const { vr, name, vm, retired } = raw[key];
    if (!STANDARD_VRS.has(vr)) {
        throw new Error(`non-standard VR '${vr}' for ${key}`);
    }
    if (!/^[A-Za-z0-9_]+$/.test(name)) {
        throw new Error(`unexpected keyword '${name}' for ${key}`);
    }
    const [vmMin, vmMax] = vm;
    lines.push(`    '${key}': ['${vr}', '${name}', ${vmMin}, ${vmMax === null ? 'null' : vmMax}, ${retired ? 1 : 0}],`);
}

const header = `/**
 * GENERATED FILE — do not edit by hand.
 *
 * PS3.6 data dictionary (${lines.length} entries), generated by
 * \`scripts/generateDictionary.mjs\` from the flat dictionary shipped in
 * \`@ubercode/dcmtk\` (\`src/data/dictionary.json\`), itself derived from
 * DCMTK's \`dicom.dic\` — Copyright OFFIS e.V., used under the DCMTK
 * (BSD-style) license. Repeating groups (overlays 60xx, retired curves 50xx)
 * are stored once under their \`60FF\`/\`50FF\` representative; the runtime
 * lookup masks them (see ./index.ts). Retired keywords keep DCMTK's
 * \`RETIRED_\` prefix.
 *
 * Regenerate: \`node scripts/generateDictionary.mjs <source.json>\` then
 * \`pnpm exec prettier --write src/dictionary/data.ts\`.
 *
 * @module dictionary/data
 */

/** Packed entry: [vr, keyword, vmMin, vmMax (null = unbounded), retired]. */
export type PackedEntry = readonly [vr: string, keyword: string, vmMin: number, vmMax: number | null, retired: 0 | 1];

/** The dictionary, keyed by 8-char uppercase hex tag (group + element). */
export const DICTIONARY_DATA: Readonly<Record<string, PackedEntry>> = {
`;

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outPath = join(scriptDir, '..', 'src', 'dictionary', 'data.ts');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, header + lines.join('\n') + '\n};\n', 'utf8');
console.log(`wrote ${outPath} (${lines.length} entries)`);
